### ISSUE TITLE
Problem of opening article.pdf

### ISSUE THREAD

**Issue by godisreal** [chraibi/jam#2]
Your article in repo of jam/data/ cannot be opened right.  When I open it online, it gets stuck.  Then I try to open it offline by acrobat reader, and it is OK at the initial 5 pages and it gets stuck when I try to read the 6th page.  Maybe you put some large pictures there?  I am not sure.  Please check the problem.  Thank you for sharing the paper.

**Comment by chraibi** [comment]
Yeah, the problem is due to large figures. I checked again the version on arxiv
https://arxiv.org/pdf/1512.01166.pdf

But it's the same problem. I  converted the file to [images](https://github.com/chraibi/jam/blob/master/data/paper.zip).

 Hope this helps.
